import test from 'node:test';import assert from 'node:assert/strict';import Stripe from 'stripe';
import {synchronize,riskEvent,webhook} from '../lib/billing.js';
const uid='11111111-1111-4111-8111-111111111111';
const sub=()=>({id:'sub_test',customer:'cus_test',metadata:{app:'fanyou',tier:'fan'},status:'active',latest_invoice:{status:'paid'},items:{data:[{quantity:1,current_period_end:1900000000,price:{id:'price_month',active:true,currency:'usd',unit_amount:1000,type:'recurring',recurring:{interval:'month',interval_count:1}}}]}});
function mockDB(){const writes=[];global.fetch=async(url,options={})=>{if(options.method==='POST'){writes.push({path:new URL(url).pathname,body:JSON.parse(options.body)});return {ok:true,json:async()=>null};}if(url.includes('fanyou_subscriptions?'))return {ok:true,json:async()=>[]};if(url.includes('fanyou_customers?'))return {ok:true,json:async()=>[{user_id:uid}]};return {ok:true,json:async()=>[]};};return writes;}
function setEnv(){process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='test';process.env.SUPABASE_SERVICE_ROLE_KEY='test';process.env.STRIPE_FAN_MONTHLY_PRICE_ID='price_month';}
test('payment snapshots require paid invoice, active status, ownership and exact price',async()=>{setEnv();const old=global.fetch;try{const writes=mockDB();let current=sub();const stripe={subscriptions:{retrieve:async()=>current}};await synchronize(stripe,'sub_test');assert.equal(writes.at(-1).body.p_status,'active');assert.equal(writes.at(-1).body.p_user,uid);current=sub();current.latest_invoice.status='open';await synchronize(stripe,'sub_test');assert.equal(writes.at(-1).body.p_status,'inactive');current=sub();current.items.data[0].price.unit_amount=100;await synchronize(stripe,'sub_test');assert.equal(writes.at(-1).body.p_status,'inactive');current=sub();current.status='canceled';await synchronize(stripe,'sub_test');assert.equal(writes.at(-1).body.p_status,'canceled');current=sub();current.pause_collection={behavior:'void'};await synchronize(stripe,'sub_test');assert.equal(writes.at(-1).body.p_status,'inactive');}finally{global.fetch=old;}});
test('full refunds resolve invoice object graph and persist a hold; partial refunds do not',async()=>{setEnv();const old=global.fetch;try{const writes=mockDB();const stripe={subscriptions:{retrieve:async()=>sub()},invoicePayments:{list:()=>({async *[Symbol.asyncIterator](){yield {invoice:'in_test'};}})},invoices:{retrieve:async()=>({parent:{type:'subscription_details',subscription_details:{subscription:'sub_test'}}})}};await riskEvent(stripe,{type:'charge.refunded',data:{object:{refunded:false,payment_intent:'pi_test'}}});assert.equal(writes.length,0);await riskEvent(stripe,{type:'charge.refunded',data:{object:{refunded:true,payment_intent:'pi_test'}}});assert.ok(writes.some(w=>w.path.endsWith('fanyou_hold_subscription')&&w.body.p_subscription==='sub_test'));}finally{global.fetch=old;}});
test('webhook verifies signature and rejects forgery before any database access',async()=>{process.env.STRIPE_SECRET_KEY='sk_test_placeholder';process.env.STRIPE_WEBHOOK_SECRET='whsec_test_placeholder';const payload=JSON.stringify({id:'evt_test',type:'unhandled.test',data:{object:{}}});await assert.rejects(webhook(Buffer.from(payload),'forged'),/Invalid webhook signature/);const signature=Stripe.webhooks.generateTestHeaderString({payload,secret:process.env.STRIPE_WEBHOOK_SECRET});assert.deepEqual(await webhook(Buffer.from(payload),signature),{received:true});});
